name: App Distribute CI

on: push

jobs:
  build_virtualevent_sample_app:
    name: Build and Distribute VirtualEvent Sample App
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - name: Prepare environment
        run: |
          git fetch --unshallow
          echo "${{ secrets.RELEASE_KEYSTORE }}" > .sign/release.keystore.asc
          gpg -d --passphrase "${{ secrets.PASSPHRASE }}" --batch .sign/release.keystore.asc > .sign/release.keystore
          echo "${{ secrets.RELEASE_KEYSTORE_PROPERTIES }}" > .sign/keystore.properties.asc
          gpg -d --passphrase "${{ secrets.PASSPHRASE }}" --batch .sign/keystore.properties.asc > .sign/keystore.properties
      - name: Assemble
        run: bash ./gradlew :virtualevent-demo:assembleRelease --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: virtualevent-demo-release
          path: virtualevent-demo/build/outputs/apk/release/
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_UI_VIRTUAL_EVENT_SAMPLE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: stream-testers
          file: virtualevent-demo/build/outputs/apk/release/virtualevent-demo-release.apk