name: Pull request CI checks

on: [pull_request]

jobs:
  lint:
    name: ktlint
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: ktlint
        run: ./gradlew ktlintCheck

  debug_build:
    name: Debug build
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        run: ./gradlew assembleDebug
